### ISSUE TITLE
Grid colors

### ISSUE THREAD

**Issue by KillyMXI** [clairefro/obsidian-plugin-chronos#27]
With default theme:

![image](https://github.com/user-attachments/assets/3b6babd4-2a86-405c-9ad9-4d535a3c3722)

![image](https://github.com/user-attachments/assets/7d9e658c-a828-4a57-b196-f8ac6341a9cb)

It clearly was only made with the light theme in mind. And even there it seems to do event colors in a somewhat wrong way.
In the dark theme, grid is more contrast than the content, making it hard to read.

Issue #13 mentions grid lines briefly, but it deserves a separate issue, so I made one here.

I only care about dark theme, so I made a CSS snippet to use Obsidian [colors](https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors) for more subtle grid.
Light theme looks barely changed.

With the snippet applied:

![image](https://github.com/user-attachments/assets/2d52e812-8a51-488d-8ecf-cb40a545b75a)

![image](https://github.com/user-attachments/assets/a0a29c77-d628-4bdd-afe1-1cfbace8cd98)

```css

.vis-label {
  color: var(--text-muted) !important;
}

.chronos-timeline-container .vis-text {
  color: var(--text-muted) !important;
}

.chronos-timeline-container :is(.vis-timeline, .vis-panel.vis-center, .vis-panel.vis-left, .vis-panel.vis-right, .vis-panel.vis-top, .vis-panel.vis-bottom) {
  border-color: var(--color-base-40);
}

.chronos-timeline-container .vis-time-axis .vis-grid.vis-major {
  border-color: var(--color-base-50);
}

.chronos-timeline-container .vis-time-axis .vis-grid.vis-minor {
  border-color: var(--color-base-35);
}

.chronos-timeline-container .vis-foreground > .vis-group,
.chronos-timeline-container .vis-labelset > .vis-label
{
  border-bottom-color: var(--color-base-40);
}

```
