### ISSUE TITLE
[feat] vertical view

### ISSUE THREAD

**Issue by colerehbein** [clairefro/obsidian-plugin-chronos#42]
this plugin is amazing, no complaints at all, amazed at the functionality. thank you for building this!

do you have plans to implement a vertical view for timelines as opposed to a horizontal view? 

thanks again!

**Comment by clairefro** [comment]
I've heard a few people interested in this. Unfortunately vertical orientation isn't an option in the vis-timeline library, and the hacky css stuff I tried isn't great, so it's not on the roadmap for now. 

```css
.chronos-timeline-container {
  transform: rotate(90deg);
  transform-origin: center;
}
```
![image](https://github.com/user-attachments/assets/ffaee738-1295-46b0-afb3-f78866171dab)


If someone is able to do this... go for it!
